### ISSUE TITLE
Binary Releases

### ISSUE THREAD

**Issue by TheDiscordian** [TheDiscordian/disco-chat#20]
Having a link to download some binary releases would be super helpful for non-developers.

**Comment by 2color** [comment]
- Windows 
- Intel Mac
- Arm Mac
- Intel Linux

**Comment by TheDiscordian** [comment]
This issue is still important, but is being removed from the "Ready-As-Example" milestone. It's a "nice to have" thing for developers, but totally not required.

**Comment by TheDiscordian** [comment]
Much of this work is happening in #31.

**Comment by TheDiscordian** [comment]
Intel Mac version runs on Arm Mac, Arm Mac can be a separate issue. This issue is likely complete, and will be closed once Linux releases are tested, and the README is updated.

**Comment by TheDiscordian** [comment]
Releases aren't yet signed, but that can be resolved on a per OS basis. Complete: https://github.com/TheDiscordian/disco-chat/releases
